[
    {
        "message": "Unexpected error: division by zero.",
        "severity": 1,
        "origin": "/media/pi/program_stick/kazanfutes/dev/dev_scripts/exception_scheme_tester.py:4",
        "origin_timestamp": "2024-09-19-23-27-00",
        "registration_timestamp": "2024-09-19-23-27-00",
        "reported": true,
        "reported_timestamp": "2024-09-19-23-27-17",
        "checked": true,
        "checked_timestamp": "2024-09-19-23-27-17"
    },
    {
        "message": "Unexpected error: division by zero.",
        "severity": 1,
        "origin": "exception_scheme_tester.py:4 --> project.py/faulty_module_function:390",
        "origin_timestamp": "2024-09-19-23-34-51",
        "registration_timestamp": "2024-09-19-23-34-51",
        "reported": true,
        "reported_timestamp": "2024-09-20-10-52-07",
        "checked": true,
        "checked_timestamp": "2024-09-20-10-52-07"
    }
]