[
    {
        "exception_type": "Test exception blabla",
        "severity": 1,
        "origin": "error_registration_tester.py:main_scope/foo:6",
        "origin_timestamp": "2024-09-18-18-09-12",
        "registration_timestamp": "2024-09-18-18-09-12",
        "reported": true,
        "reported_timestamp": "2024-09-18-18-09-21",
        "checked": true,
        "checked_timestamp": "2024-09-18-18-09-21"
    }
]