{"timestamp": "2025-01-23-17-13-36", "message": "Module error while trying to update local heating control config: failed to set up Google Sheets API: [Errno 2] No such file or directory: '/media/pi/program_stick/kazanfutes/config/secrets_and_env/sheets-access-key.json' (FileNotFoundError).", "severity": 2, "origin": "schedule_and_config_updater.py/update_local_heating_control_config:88 --> project.py/download_google_sheet_to_2D_array:1596", "origin_timestamp": "2025-01-23-17-05-44", "registration_timestamp": "2025-01-23-17-05-44"}
{"timestamp": "2025-01-23-17-25-05", "message": "Module error while trying to scrape and log external temperature: error during external temperature scraping: HTTPSConnectionPool(host='api.open-meteo.com', port=443): Max retries exceeded with url: /v1/forecast?latitude=47.4984&longitude=19.0405&current_weather=true (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0xf53b4ab0>: Failed to resolve 'api.open-meteo.com' ([Errno -3] Temporary failure in name resolution)\")) (ConnectionError).", "severity": 2, "origin": "external_temp_scraper_and_logger.py:9 --> project.py/scrape_external_temperature:622", "origin_timestamp": "2025-01-23-17-20-26", "registration_timestamp": "2025-01-23-17-20-26"}
