{"timestamp": "2025-02-04-11-35-04", "message": "Module error while trying to scrape and log external temperature: error during external temperature scraping: HTTPSConnectionPool(host='api.open-meteo.com', port=443): Max retries exceeded with url: /v1/forecast?latitude=47.4984&longitude=19.0405&current_weather=true (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0xf5734b50>: Failed to resolve 'api.open-meteo.com' ([Errno -3] Temporary failure in name resolution)\")) (ConnectionError).", "severity": 2, "origin": "external_temp_scraper_and_logger.py:9 --> project.py/scrape_external_temperature:623", "origin_timestamp": "2025-02-04-11-30-15", "registration_timestamp": "2025-02-04-11-30-15"}
{"timestamp": "2025-02-04-17-20-04", "message": "Module error while extracting room KPIs for 2025-02-04.: 'on'.", "severity": 2, "origin": "data_formatter.py:466", "origin_timestamp": "2025-02-04-17-15-28", "registration_timestamp": "2025-02-04-17-15-28"}
